const products = [
  {
    id: 1,
    category: 'electronics',
    brand: 'SonicWave',
    title: 'Active Noise Cancelling Headphones',
    description: 'Wireless over-ear headphones with balanced sound, adaptive noise cancellation, and premium comfort.',
    price: 199.99,
    priceOld: 249.99,
    discount: 20,
    rating: 4.8,
    reviews: 342,
    stock: 18,
    badge: 'Best Seller',
    image: 'heaphone.jpg',
    alt: 'White wireless headphones with premium design'
  },
  {
    id: 2,
    category: 'electronics',
    brand: 'HomeSense',
    title: 'Smart Home Display Hub',
    description: 'Voice-controlled smart display for home automation, schedules, and video calling.',
    price: 129.99,
    discount: 10,
    rating: 4.5,
    reviews: 181,
    stock: 24,
    badge: 'Limited Offer',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    alt: 'Smart home display on a modern desk'
  },
  {
    id: 3,
    category: 'fashion',
    brand: 'AeroForm',
    title: 'Minimalist Leather Sneakers',
    description: 'Lightweight leather sneakers with premium cushioning designed for everyday comfort.',
    price: 89.0,
    rating: 4.7,
    reviews: 279,
    stock: 7,
    badge: 'Best Seller',
    image: 'sneaker.jpg',
    alt: 'Pair of minimalist leather sneakers on a white floor'
  },
  {
    id: 4,
    category: 'fashion',
    brand: 'Noble Thread',
    title: 'Tailored Wool Coat',
    description: 'Slim-fit wool coat with a refined silhouette, polished buttons, and premium finish.',
    price: 149.99,
    rating: 4.6,
    reviews: 214,
    stock: 12,
    badge: 'Premium pick',
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80',
    alt: 'Dark wool coat draped on a wooden chair'
  },
  {
    id: 5,
    category: 'home',
    brand: 'LumaLiving',
    title: 'Modern Ceramic Table Lamp',
    description: 'Soft matte ceramic lamp with warm LED glow for luxurious living room ambiance.',
    price: 64.0,
    discount: 15,
    rating: 4.9,
    reviews: 124,
    stock: 29,
    badge: 'Popular',
    image: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=800&q=80',
    alt: 'Ceramic table lamp by a cozy sofa'
  },
  {
    id: 6,
    category: 'home',
    brand: 'Oak & Co',
    title: 'Oak Wood Side Table',
    description: 'Compact side table crafted in solid oak with a concealed storage drawer.',
    price: 109.5,
    rating: 4.4,
    reviews: 98,
    stock: 14,
    image: 'https://images.unsplash.com/photo-1493666438817-866a91353ca9?auto=format&fit=crop&w=800&q=80',
    alt: 'Oak side table with modern decor'
  },
  {
    id: 7,
    category: 'fitness',
    brand: 'Luxe Fit',
    title: 'Portable Resistance Bands Set',
    description: 'Lightweight resistance bands for home cardio and strength training with premium carry case.',
    price: 29.95,
    rating: 4.9,
    reviews: 448,
    stock: 32,
    badge: 'Value buy',
    image: 'resistance-bands.jpg',
    alt: 'Resistance bands on a hardwood floor'
  },
  {
    id: 8,
    category: 'fitness',
    brand: 'PulsePro',
    title: 'Smart Fitness Watch',
    description: 'Water-resistant activity tracker with workout metrics, sleep monitoring, and crisp display.',
    price: 169.0,
    priceOld: 189.0,
    discount: 11,
    rating: 4.7,
    reviews: 197,
    stock: 21,
    badge: 'Best Seller',
    image: 'https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b?auto=format&fit=crop&w=800&q=80',
    alt: 'Fitness watch with activity tracking display'
  },
  {
    id: 9,
    category: 'beauty',
    brand: 'Aurora Skin',
    title: 'Serene Skincare Collection',
    description: 'Daily skincare set with moisturizers and nourishing botanical formulas for glowing skin.',
    price: 58.5,
    rating: 4.6,
    reviews: 164,
    stock: 28,
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=80',
    alt: 'Serene skincare products arranged on marble'
  },
  {
    id: 10,
    category: 'beauty',
    brand: 'GlowMist',
    title: 'Refresh Facial Mist',
    description: 'Cooling facial mist that hydrates skin with natural antioxidants.',
    price: 22.0,
    rating: 4.7,
    reviews: 198,
    stock: 55,
    image: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=800&q=80',
    alt: 'Facial mist spray bottle on a bright background'
  },
  {
    id: 11,
    category: 'electronics',
    brand: 'PulseAudio',
    title: 'Compact Bluetooth Speaker',
    description: 'Portable speaker with crisp sound and deep bass for indoor or outdoor use.',
    price: 79.0,
    rating: 4.5,
    reviews: 210,
    stock: 20,
    image: 'https://images.unsplash.com/photo-1509395176047-4a66953fd231?auto=format&fit=crop&w=800&q=80',
    alt: 'Compact Bluetooth speaker with modern design'
  },
  {
    id: 12,
    category: 'fashion',
    brand: 'Nomad Pack',
    title: 'Everyday Travel Backpack',
    description: 'Durable travel backpack with padded laptop compartment and organizer pockets.',
    price: 59.99,
    rating: 4.4,
    reviews: 184,
    stock: 16,
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    alt: 'Travel backpack placed near home entrance'
  },
  {
    id: 13,
    category: 'home',
    brand: 'CloudRest',
    title: 'Luxury Sheet Set',
    description: 'Breathable cotton sheet set with a silky finish for a restful night.',
    price: 74.0,
    rating: 4.8,
    reviews: 103,
    stock: 30,
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
    alt: 'Neatly folded luxury sheet set on a bed'
  },
  {
    id: 14,
    category: 'fitness',
    brand: 'EcoFlow',
    title: 'Recycled Yoga Mat',
    description: 'Eco-friendly yoga mat with enhanced grip and premium cushioning.',
    price: 39.5,
    rating: 4.6,
    reviews: 142,
    stock: 19,
    image: 'yoga-mat.jpg',
    alt: 'Person practicing yoga on a recycled mat'
  },
  {
    id: 15,
    category: 'beauty',
    brand: 'SilkRoot',
    title: 'Luxury Hair Styling Set',
    description: 'Salon-quality styling essentials for silky shine and easy glide.',
    price: 49.99,
    rating: 4.7,
    reviews: 121,
    stock: 25,
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80',
    alt: 'Hair styling products arranged neatly'
  },
  {
    id: 16,
    category: 'electronics',
    brand: 'Elevate',
    title: 'Premium Laptop Stand',
    description: 'Ergonomic laptop stand with adjustable height and aluminum finish.',
    price: 44.0,
    rating: 4.3,
    reviews: 83,
    stock: 22,
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80',
    alt: 'Laptop stand on desk with open laptop'
  },
  {
    id: 17,
    category: 'home',
    brand: 'Aria Decor',
    title: 'Modern Wall Art Print',
    description: 'Abstract wall art print framed for contemporary room styling.',
    price: 36.0,
    rating: 4.5,
    reviews: 67,
    stock: 26,
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=80',
    alt: 'Abstract wall art print above a sofa'
  },
  {
    id: 18,
    category: 'fashion',
    brand: 'SkyShade',
    title: 'Classic Aviator Sunglasses',
    description: 'UV-protective aviator sunglasses finished with polished metal details.',
    price: 69.0,
    rating: 4.6,
    reviews: 156,
    stock: 13,
    badge: 'Limited Offer',
    image: 'https://images.unsplash.com/photo-1516637090014-cb1ab78511f5?auto=format&fit=crop&w=800&q=80',
    alt: 'Classic aviator sunglasses on a wooden table'
  },
  {
    id: 19,
    category: 'fitness',
    brand: 'SprintPods',
    title: 'Wireless Earbuds for Running',
    description: 'Sweat-resistant earbuds with secure fit, powerful audio, and long battery life.',
    price: 94.0,
    rating: 4.7,
    reviews: 232,
    stock: 17,
    image: 'https://images.unsplash.com/photo-1511367461989-f85a21fda167?auto=format&fit=crop&w=800&q=80',
    alt: 'Wireless earbuds in charging case'
  },
  {
    id: 20,
    category: 'beauty',
    brand: 'Vital Glow',
    title: 'Daily Vitamin Serum',
    description: 'Vitamin-infused serum to brighten skin, improve hydration, and restore radiance.',
    price: 32.0,
    rating: 4.6,
    reviews: 139,
    stock: 41,
    image: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=800&q=80',
    alt: 'Vitamin serum bottle next to green leaves'
  }
];
